[package]
name = "coll"
version = "0.1.0"
authors = ["Jim D'Angelo", "Funclobile, Inc."]
description = "Some basic (persistent) collections"
license-file = "LICENSE"
repository = "https://github.com/dangeloj/rust-collections"

[dependencies]
